### Broadcasting


<style>
    .font12 { font-size: 12px; }
</style>

<div class="font12">
    
    

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.
</div>



In [111]:
import numpy as np

In [160]:
arr1=np.arange(3)
arr1

array([0, 1, 2])

In [162]:
arr2=(np.ones((2,3))).astype(int)
arr2

array([[1, 1, 1],
       [1, 1, 1]])

In [164]:
arr1.shape

(3,)

In [166]:
arr2.shape

(2, 3)

In [168]:
#rule 1: We pad with one at its left.
arr2.shape=(2,3)
arr2

array([[1, 1, 1],
       [1, 1, 1]])

In [170]:
arr1.shape=(1,3)
arr1

array([[0, 1, 2]])

In [187]:
arr1.reshape((3,1)) #Padding
arr1

array([[0, 1, 2]])

In [196]:
a=np.arange(1,7).reshape((3,2))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [202]:
A=np.ones((2,3))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [214]:
B=np.arange(3)
B

array([0, 1, 2])

In [216]:
A+B

array([[1., 2., 3.],
       [1., 2., 3.]])

In [242]:
X=np.arange(3)
print(X)
print(f"Shape of X is {X.shape}")

[0 1 2]
Shape of X is (3,)


In [244]:
Y=np.arange(3).reshape(3,1)
print(Y)
print(f"Shape of Y is {Y.shape}")

[[0]
 [1]
 [2]]
Shape of Y is (3, 1)


In [248]:
S=X+Y
print(S)
print(f"Shape of S is {S.shape}")

[[0 1 2]
 [1 2 3]
 [2 3 4]]
Shape of S is (3, 3)
